version: '2'

# #configuration of maintainability checks
checks:
  # methods or functions defined with a high number of arguments
  argument-count:
    config:
      threshold: 4

  # boolean logic that may be hard to understand
  complex-logic:
    config:
      threshold: 4

  # excessive lines of code within a single file
  file-lines:
    config:
      threshold: 250

  # functions or methods that may be hard to understand aka cognitiv complexity
  method-complexity:
    config:
      threshold: 6

  # classes defined with a high number of functions or methods
  method-count:
    config:
      threshold: 20

  # excessive lines of code within a single function or method
  method-lines:
    config:
      threshold: 42

  # deeply nested control structures like if or case
  nested-control-flow:
    config:
      threshold: 4

  # functions or methods with a high number of return statements
  return-statements:
    config:
      threshold: 4

  # duplicate code which is not identical but shares the same structure
  similar-code:
    config:
      # threshold is language-specific
      threshold:
  # ctrl-c ctrl-v :(
  identical-code:
    config:
      threshold:
