export const plantConstants = {
	SEARCH_PLANT_BY_IMG_REQUEST: 'SEARCH_PLANT_BY_IMG_REQUEST',
	SEARCH_PLANT_BY_IMG_SUCCESS: 'SEARCH_PLANT_BY_IMG_SUCCESS',
	SEARCH_PLANT_BY_IMG_FAILURE: 'SEARCH_PLANT_BY_IMG_FAILURE',

	SEARCH_PLANT_BY_NAME_REQUEST: 'SEARCH_PLANT_BY_NAME_REQUEST',
	SEARCH_PLANT_BY_NAME_SUCCESS: 'SEARCH_PLANT_BY_NAME_SUCCESS',
	SEARCH_PLANT_BY_NAME_FAILURE: 'SEARCH_PLANT_BY_NAME_FAILURE',
};
