export const plantConstants = {
	SEARCH_PLANT_BY_IMG_REQUEST: 'SEARCH_PLANT_BY_IMG_REQUEST',
	SEARCH_PLANT_BY_IMG_SUCCESS: 'SEARCH_PLANT_BY_IMG_SUCCESS',
	SEARCH_PLANT_BY_IMG_FAILURE: 'SEARCH_PLANT_BY_IMG_FAILURE',

	SEARCH_PLANT_BY_NAME_REQUEST: 'SEARCH_PLANT_BY_NAME_REQUEST',
	SEARCH_PLANT_BY_NAME_SUCCESS: 'SEARCH_PLANT_BY_NAME_SUCCESS',
	SEARCH_PLANT_BY_NAME_FAILURE: 'SEARCH_PLANT_BY_NAME_FAILURE',

	GET_PLANT_BDD_REQUEST: 'GET_PLANT_BDD_REQUEST',
	GET_PLANT_BDD_SUCCESS: 'GET_PLANT_BDD_SUCCESS',
	GET_PLANT_BDD_FAILURE: 'GET_PLANT_BDD_FAILURE',

	GET_BY_ID_PLANT_BDD_REQUEST: 'GET_BY_ID_PLANT_BDD_REQUEST',
	GET_BY_ID_PLANT_BDD_SUCCESS: 'GET_BY_ID_PLANT_BDD_SUCCESS',
	GET_BY_ID_PLANT_BDD_FAILURE: 'GET_BY_ID_PLANT_BDD_FAILURE',

	POST_PLANT_BDD_REQUEST: 'POST_PLANT_BDD_REQUEST',
	POST_PLANT_BDD_SUCCESS: 'POST_PLANT_BDD_SUCCESS',
	POST_PLANT_BDD_FAILURE: 'POST_PLANT_BDD_FAILURE',

	UPDATE_BY_ID_PLANT_BDD_REQUEST: 'UPDATE_BY_ID_PLANT_BDD_REQUEST',
	UPDATE_BY_ID_PLANT_BDD_SUCCESS: 'UPDATE_BY_ID_PLANT_BDD_SUCCESS',
	UPDATE_BY_ID_PLANT_BDD_FAILURE: 'UPDATE_BY_ID_PLANT_BDD_FAILURE',

	DELETE_BY_ID_PLANT_BDD_REQUEST: 'DELETE_BY_ID_PLANT_BDD_REQUEST',
	DELETE_BY_ID_PLANT_BDD_SUCCESS: 'DELETE_BY_ID_PLANT_BDD_SUCCESS',
	DELETE_BY_ID_PLANT_BDD_FAILURE: 'DELETE_BY_ID_PLANT_BDD_FAILURE',

	GET_PLANT_REQUEST: 'GET_PLANT_REQUEST',
	GET_PLANT_SUCCESS: 'GET_PLANT_SUCCESS',
	GET_PLANT_FAILURE: 'GET_PLANT_FAILURE',

	POST_PLANT_BDD_CLEAN: 'POST_PLANT_BDD_CLEAN',
};
